### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Zamanry** [topotam/PetitPotam#20]
Hello, my employer would like to use your code as a part of our penetration tests. Not to distribute, but use. Could you add an appropriate license to allow this OR at least provide a license to clarify your software usage? Thanks!

**Comment by topotam** [comment]
Hello,
My code is free to be used for anything, you can use it, distribute it, modify it, use it in commercial product, etc. all you want for free without having my explicit autorization :). Just one thing is if you include it in a commercial product, don't remove the author's credit strings in the code(by @Topotam).
